### ISSUE TITLE
Error when I'm trying to build IOS and android V 1.7.0

### ISSUE THREAD

**Issue by Basim-Elayan** [danielgek/nativescript-sentry#23]
I got this error message once I tried to build has sentry.
```Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Error: Can't resolve all parameters for SentryErrorHandler: (?)```

**Comment by Basim-Elayan** [comment]
So I'm working on nativescript using angular but:
Without Angular `-------This is working for me just on IOS`
import { Sentry } from 'nativescript-sentry';
const dsn = 'https://<key>:<secret>@host/<project>';
Sentry.init(dsn);
With Angular ` -------Using this way I got that earlier error.`
import { SentryModule } from 'nativescript-sentry/angular';

NgModule({
  ...
  imports: [
       SentryModule.forRoot({dsn: 'https://<key>:<secret>@host/<project>'})
  ],

**Comment by Basim-Elayan** [comment]
The above solution doesn't work on android I got error message
```ReferenceError: io is not defined```

**Comment by danielgek** [comment]
fixed in 1.7.1

**Comment by Basim-Elayan** [comment]
I'll try it Thanks.

**Comment by carlosen14** [comment]
I'm still facing  `io is not defined` on Android w/ Angular
Using: `"nativescript-angular": "~7.2.1", "nativescript-sentry": "1.9.1"`


```
io is not defined

ReferenceError: io is not defined
    at Function.Sentry.init (file:///data/data/org.nativescript.mobilesicdh2/files/app/tns_modules/nativescript-sentry/sentry.js:8:9)
    at new SentryErrorHandler (file:///data/data/org.nativescript.mobilesicdh2/files/app/tns_modules/nativescript-sentry/angular/error.handler.js:12:24)
    at provideSentryServiceOptions (file:///data/data/org.nativescript.mobilesicdh2/files/app/tns_modules/nativescript-sentry/angular/app.module.js:31:12)
    at _callFactory (file:///data/data/org.nativescript.mobilesicdh2/files/app/tns_modules/@angular/core/bundles/core.umd.js:21205:24)
    at _createProviderInstance (file:///data/data/org.nativescript.mobilesicdh2/files/app/tns_modules/@angular/core/bundles/core.umd.js:21161:30)
    at initNgModule (file:///data/data/org.nativescript.mobilesicdh2/files/app/tns_modules/@angular/core/bundles/core.umd.js:21091:36)
    at new NgModuleRef_ (file:///data/data/org.nativescript.mobilesicdh2/files/app/tns_modules/@angular/core/bundles/core.umd.js:21818:13)
    at createNgModuleRef (file:///data/data/org.nativescript.mobilesicdh2/files/app/tns_modules/@angular/core/bundles/core.umd.js:21807:16)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (file:///data/data/org.nativescript.mobilesicdh2/files/app/tns_modules/@angular/core/bundles/core.umd.js:23638:16)
    at NgModuleFactory_.create (file:///data/data/org.nativescript.mobilesicdh2/files/app/tns_modules/@angular/core/bundles/core.umd.js:24342:29)
    at file:///data/data/org.nativescript.mobilesicdh2/files/app/tns_modules/@angular/core/bundles/core.umd.js:17800:47
    at ZoneDelegate.invoke (file:///data/data/org.nativescript.mobilesicdh2/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:388:26)
    at Object.onInvoke (file:///data/data/org.nativescript.mobilesicdh2/files/app/tns_modules/@angular/core/bundles/core.umd.js:17334:37)
    at ZoneDelegate.invoke (file:///data/data/org.nativescript.mobilesicdh2/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:387:32)
    at Zone.run (file:///data/data/org.nativescript.mobilesicdh2/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:138:43)
```

`sentry.js`
````js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var utils = require("tns-core-modules/utils/utils");
var Sentry = (function () {
    function Sentry() {
    }
    Sentry.init = function (dsn) {
        /*ERROR here >> */ io.sentry.Sentry.init(dsn, new io.sentry.android.AndroidSentryClientFactory(utils.ad.getApplicationContext()));
    };
//...
)}
```

**Comment by carlosen14** [comment]
Any new?? still having the problem with 1.9.1 from tns plugin registry
